# keymap.toml
# https://yazi-rs.github.io/docs/configuration/keymap

# toggle-pane: preview を全画面トグル
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
