# yazi.toml
# https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
ratio = [1, 2, 5]
show_hidden = true

[plugin]
prepend_previewers = [
  { url = "*.csv", run = "duckdb" },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb" },
]
